version: "3.7"
services:
  go-server:
    image: gz-locker-server
    ports:
      - "5068:5000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '250MB'
        reservations:
          cpus: '0.5'
          memory: '100MB'
