version: "3.7"
services:
  go-server:
    image: ghcr.io/hocptit/luniand-go-be:latest
    ports:
      - "5168:5168"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '1050MB'
        reservations:
          cpus: '0.5'
          memory: '500MB'
    networks:
      - luniand-dev

networks:
  luniand-dev:
    external: true