name: validate-lint-when make pull request
run-name: ${{ github.actor }} is validating eslint.

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  validate-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - uses: docker
      - name: Using docker to check eslint
        run: |
          echo "Start lint...."
          docker run -v $(pwd):/app -w /app golangci/golangci-lint:v1.50.1 golangci-lint  run -c .golangci.yaml ./...
          echo "Lint done."